package com.qrpayments.bridge

import com.qrpayments.data.BankAccount

/**
 * Bridge to Swift QRPaymentsCore library
 *
 * TODO: This will be generated by swift-java tooling
 * For now, we provide a Kotlin implementation that mirrors the Swift logic
 */
object SwiftBridge {

    /**
     * Generates SPAYD format string for Czech QR payment
     * Calls Swift SPAYDGenerator.generate() via swift-java
     */
    fun generateSPAYD(
        prefix: String,
        accountNumber: String,
        bankCode: String,
        amount: String?,
        variableSymbol: String?,
        message: String?
    ): String {
        // TODO: Replace with swift-java generated call to Swift SPAYDGenerator
        // For now, use Kotlin implementation
        return generateSPAYDKotlin(prefix, accountNumber, bankCode, amount, variableSymbol, message)
    }

    /**
     * Validates bank code (4 digits)
     */
    fun isValidBankCode(code: String): Boolean {
        // TODO: Replace with swift-java call to Swift Validator
        return code.length == 4 && code.all { it.isDigit() }
    }

    /**
     * Validates account number (up to 10 digits)
     */
    fun isValidAccountNumber(number: String): Boolean {
        // TODO: Replace with swift-java call to Swift Validator
        return number.isNotEmpty() && number.length <= 10 && number.all { it.isDigit() }
    }

    /**
     * Validates account prefix (optional, up to 6 digits)
     */
    fun isValidPrefix(prefix: String): Boolean {
        // TODO: Replace with swift-java call to Swift Validator
        if (prefix.isEmpty()) return true
        return prefix.length <= 6 && prefix.all { it.isDigit() }
    }

    /**
     * Temporary Kotlin implementation of SPAYD generation
     * This mirrors the Swift logic and will be replaced by swift-java bridge
     */
    private fun generateSPAYDKotlin(
        prefix: String,
        accountNumber: String,
        bankCode: String,
        amount: String?,
        variableSymbol: String?,
        message: String?
    ): String {
        val iban = convertToIBAN(prefix, accountNumber, bankCode)
        val components = mutableListOf<String>()

        // Required: Version and Account
        components.add("SPD*1.0")
        components.add("ACC:$iban")

        // Optional: Amount
        if (!amount.isNullOrEmpty()) {
            amount.toDoubleOrNull()?.let { amountValue ->
                if (amountValue > 0) {
                    components.add("AM:${"%.2f".format(amountValue)}")
                }
            }
        }

        // Required: Currency
        components.add("CC:CZK")

        // Optional: Message
        if (!message.isNullOrEmpty()) {
            val encodedMessage = message.replace(Regex("[^A-Za-z0-9]"), "")
            components.add("MSG:$encodedMessage")
        }

        // Optional: Variable Symbol
        if (!variableSymbol.isNullOrEmpty()) {
            components.add("X-VS:$variableSymbol")
        }

        return components.joinToString("*")
    }

    /**
     * Converts Czech account format to IBAN
     */
    private fun convertToIBAN(prefix: String, accountNumber: String, bankCode: String): String {
        // Pad prefix to 6 digits
        val paddedPrefix = if (prefix.isEmpty()) {
            "000000"
        } else {
            prefix.toIntOrNull()?.let { "%06d".format(it) } ?: "000000"
        }

        // Pad account number to 10 digits
        val paddedAccount = accountNumber.toIntOrNull()?.let { "%010d".format(it) } ?: "0000000000"

        // Combine bank code + prefix + account
        val bban = "$bankCode$paddedPrefix$paddedAccount"

        // Calculate IBAN check digits
        val checkDigits = calculateIBANCheckDigits("CZ", bban)

        return "CZ$checkDigits$bban"
    }

    /**
     * Calculates IBAN check digits using MOD 97 algorithm
     */
    private fun calculateIBANCheckDigits(countryCode: String, bban: String): String {
        // Move country code and 00 to the end
        val rearranged = bban + countryCode + "00"

        // Replace letters with numbers (A=10, B=11, ..., Z=35)
        val numericString = buildString {
            for (char in rearranged) {
                if (char.isLetter()) {
                    append(char.code - 'A'.code + 10)
                } else {
                    append(char)
                }
            }
        }

        // Calculate MOD 97
        var remainder = 0
        for (char in numericString) {
            remainder = (remainder * 10 + char.digitToInt()) % 97
        }

        val checkDigit = 98 - remainder
        return "%02d".format(checkDigit)
    }
}
